FROM openjdk:21
LABEL maintainer="itsupport@gmail.com"
ADD target/demo-coingecko-0.0.1-SNAPSHOT.jar demo-coingecko-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "demo-coingecko-0.0.1-SNAPSHOT.jar"]
EXPOSE 8085