server:
  port: 8081

service:
  finnhub:
    host: "localhost:8080"
    quote:
      version: ""
      endpoint: "/stock"

spring.datasource:
  driverClassName: "org.postgresql.Driver"
  url: "jdbc:postgresql://localhost:5432/bootcamp_2504"
  username: "postgres"
  password: "admin1234"

spring.jpa:
  show-sql: true
  hibernate.ddl-auto: update

spring:
  data:
    redis:
      host: localhost
      port: 6379
