FROM openjdk:21
LABEL maintainer="itsupport@gmail.com"
ADD target/demo-crypto-0.0.1-SNAPSHOT.jar demo-crypto-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "demo-crypto-0.0.1-SNAPSHOT.jar"]
EXPOSE 8086